### ISSUE TITLE
兄弟，稳呢！

### ISSUE THREAD

**Issue by zry9815** [tanglaoban/NIIT-jktb#1]
表白墙看到的 star了

**Comment by tanglaoban** [comment]
> 表白墙看到的星星
不是本人发布的，代码一年前所写，仅发给了部分同学

**Comment by zry9815** [comment]
https://github.com/ybm911/FUCK_jiankangdaka 之前看到过这个 修改起来太复杂了

**Comment by bloodniu** [comment]
几个参数，修改一下就可以了

**Comment by zry9815** [comment]
主程序里面只要加xxx yyy  zzz三个识别码吗 运行不起来 报错
C:\Users\Zry\AppData\Local\Programs\Python\Python39\python.exe C:/Users/Zry/Desktop/NIIT-jktb-main/jktb.py
Traceback (most recent call last):
  File "C:\Users\Zry\Desktop\NIIT-jktb-main\jktb.py", line 11, in <module>
    import yaml
  File "C:\Users\Zry\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\__init__.py", line 2, in <module>
    from error import *
ModuleNotFoundError: No module named 'error'

**Comment by bloodniu** [comment]
是否配置了环境呢？

**Comment by zry9815** [comment]
xxx yyy zzz三个变量后面的注释错了 xxx和yyy对应的代码反了 然后这是什么情况

INFO:root: ** Get ready ** 
INFO:root: ** jktb开始 ** 
 当前经度：xxx
 当前纬度：xxx
200
200
200
200
200
200
200
 get if seccess 200
INFO:root: all ready to start ! 
200
 get id xxx
 get Class xxx
 get email xxx
 get sex xxx
 get telephone xxx
 get grade xxx
 get sdept 22.机械xxx
Traceback (most recent call last):
  File "C:/Users/Zry/Desktop/NIIT-jktb-main/jktb.py", line 470, in <module>
    Province = ast.literal_eval(re.text)['value']['province']
KeyError: 'value'

好像是位置的问题

**Comment by zry9815** [comment]
xxx yyy zzz三个变量后面的注释错了 xxx和yyy对应的代码反了 然后这是什么情况

INFO:root: ** Get ready ** 
INFO:root: ** jktb开始 ** 
 当前经度：xxx
 当前纬度：xxx
200
200
200
200
200
200
200
 get if seccess 200
INFO:root: all ready to start ! 
200
 get id xxx
 get Class xxx
 get email xxx
 get sex xxx
 get telephone xxx
 get grade xxx
 get sdept 22.机械xxx
Traceback (most recent call last):
  File "C:/Users/Zry/Desktop/NIIT-jktb-main/jktb.py", line 470, in <module>
    Province = ast.literal_eval(re.text)['value']['province']
KeyError: 'value'

好像是位置的问题

**Comment by bloodniu** [comment]
20级别用

**Comment by zry9815** [comment]
好吧 原来是这样

**Comment by bloodniu** [comment]
其实都能用，自己动动脑子，本文仅限学习参考

**Comment by zry9815** [comment]
行 我再琢磨琢磨 谢谢啦
